### ISSUE TITLE
Add run guide in README

### ISSUE THREAD

**Issue by spaceh3ad** [j4ys0n/evmdecoder#1]
This tool look awesome, thanks for sharing it, however am unable to run it.
I checked package.json for run scripts couldn't find one. 
I am not really into typescript :)
Thanks!

**Comment by j4ys0n** [comment]
It's meant to be installed with npm/yarn, but yes i'll add instructions to run locally for development/contributions.

**Comment by j4ys0n** [comment]
The readme has been updated with information on how to use the package and how to set up a dev environment.
https://github.com/j4ys0n/evmdecoder#how-to-use
https://github.com/j4ys0n/evmdecoder#dev-setup
